# Generated by Django 2.2.1 on 2019-05-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stonebase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FilePathField(path='/image')),
            ],
        ),
    ]
