# Generated by Django 2.2.1 on 2019-05-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190520_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stonebase',
            new_name='Stone',
        ),
    ]
