# Generated by Django 2.2.1 on 2019-05-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_stone_shortdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='images2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stone',
            name='images3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
